[build]
  command = "cd demo && bundle install && bundle exec jekyll build"
  publish = "demo/_site"

[build.environment]
  JEKYLL_ENV = "production"

[[plugins]]
  package = "../index.js"

  [plugins.inputs]
    ghostURL = "https://demo.ghost.io"
    ghostKey = "22444f78447824223cefc48062"
    assetsDir = "./demo/assets/images/"
    pagesDir = "./demo/"
    postsDir = "./demo/_posts/"

