[build]
  command = "npm run clonePlugin && cd test && bundle install && bundle exec jekyll build"
  publish = "test/_site"

[build.environment]
  JEKYLL_ENV = "production"

[[plugins]]
package = "./test/plugins/index.js"

  [plugins.inputs]
  ghostURL = "https://demo.ghost.io"
  ghostKey = "22444f78447824223cefc48062"
  assetsDir = "./test/assets/images/"
  pagesDir = "./test/"
  postsDir = "./test/_posts/"
  cacheFile = "./test/_data/ghostMarkdownCache.json"
